/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CreatorButton: typeof import('./components/creator-button/index.vue')['default']
    Draw: typeof import('./components/draw/index.vue')['default']
    Menu: typeof import('./components/menu/Menu.vue')['default']
    Note: typeof import('./components/note/index.vue')['default']
    Outline: typeof import('./components/outline/index.vue')['default']
    Preview: typeof import('./components/markdown/Preview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubmitArticleDlg: typeof import('./components/dlg/SubmitArticleDlg.vue')['default']
    TagInput: typeof import('./components/tag/TagInput.vue')['default']
    Tooltips: typeof import('./components/tooltips/index.vue')['default']
    UserToolTip: typeof import('./components/tooltips/components/UserToolTip.vue')['default']
  }
}
